// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbw3GjdmOUp4rHoAw20q3bIN46x1473cw',
    appId: '1:62953839404:web:6fb7490c6b36514623aa89',
    messagingSenderId: '62953839404',
    projectId: 'fourthfirebase-1e90b',
    authDomain: 'fourthfirebase-1e90b.firebaseapp.com',
    storageBucket: 'fourthfirebase-1e90b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49XoxIHDjemHcLzEmPbi2mVaMuFaBMpg',
    appId: '1:62953839404:android:073d12f980c00ee023aa89',
    messagingSenderId: '62953839404',
    projectId: 'fourthfirebase-1e90b',
    storageBucket: 'fourthfirebase-1e90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYs9Xdk07Nj1J60Klz8dmTRV_W5OF1c6s',
    appId: '1:62953839404:ios:f9dfabbd4fb470d323aa89',
    messagingSenderId: '62953839404',
    projectId: 'fourthfirebase-1e90b',
    storageBucket: 'fourthfirebase-1e90b.appspot.com',
    iosBundleId: 'com.example.petcarep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYs9Xdk07Nj1J60Klz8dmTRV_W5OF1c6s',
    appId: '1:62953839404:ios:894e5e8be85c92c623aa89',
    messagingSenderId: '62953839404',
    projectId: 'fourthfirebase-1e90b',
    storageBucket: 'fourthfirebase-1e90b.appspot.com',
    iosBundleId: 'com.example.petcarep.RunnerTests',
  );
}
